defaults:
  - setup
  - target: funnel
  - interpolant: linearInterpolant
  - hjb_solver: fbsde
  - model@score_model: eDISnet
  - model@velocity_model: ${model@score_model}
  - _self_
  - long_run

#target:
#  var: 0.3
#  mean: 5.0

seed: 1
T: 1.0
T0: 0.5
dim: ${target.d}
eps0: 1e-5
eps1: 1e-5
batch_size: 128
log_interval: 10
eval_interval: 2000
ckpt_interval: 500
jit_lossFn: 1
learn_potential: 0

train:
  NtTrain: 20
  epochs: 3000
  epoch_steps: 3
  learning_rate: 1.0e-3
  scheduler_scale: 0.5
  scheduler_step: 1000
  tval_ramp_time: 1500
  grad_norm: 1.0

interpolant:
  type: trig

solver:
  _target_: stint_sampler.stint.sis.full_sis

sampler:
  Nsamples: 10000
  NtSampler: 1000

pde_solver:
  scale_init_train: 1.0
  train_sde_drift: 0.0
  time_step: 1e-6

eval:
  hist_dims: [0,1]