defaults:
  - setup
  - target: gmm
  - interpolant: linearInterpolant
  - hjb_solver: fbsde
  - model: eDISnet
  - _self_

seed: 1
T: 1.0
dim: ${target.d}
eps0: 1e-5
eps1: 1e-5
batch_size: 512
log_interval: 10
eval_interval: 100
jit_lossFn: 1

train:
  NtTrain: 50
  epochs: 5000
  epoch_steps: 4
  learning_rate: 1e-2

interpolant:
  type: trig

solver:
  _target_: stint_sampler.stint.sis.half_sis

sampler:
  Nsamples: 10000
  NtSampler: 1000

pde_solver:
  scale_init_train: 0.01
  train_sde_drift: 0.00

eval:
  hist_dims: [0,1]